 
package com.yougou.merchant.api.supplier.vo;

import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.lang.StringUtils;

public class MerchantSupplierExpandQuery {
    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_supplier_expand
     *
     * @yougougenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_supplier_expand
     *
     * @yougougenerated
     */
    protected String oderProperty;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_supplier_expand
     *
     * @yougougenerated
     */
    protected String oderType;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_supplier_expand
     *
     * @yougougenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_supplier_expand
     *
     * @yougougenerated
     */
    protected List<Criteria> oredCriteria;

    public MerchantSupplierExpandQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        if (StringUtils.isEmpty(orderByClause) && StringUtils.isNotEmpty(this.getOderProperty()) && StringUtils.isNotEmpty(this.getOderType())){
            return MessageFormat.format("{0} {1}", this.getOderProperty(),this.getOderType());
        }
        return orderByClause;
    }

    public void setOderProperty(String oderProperty) {
        this.oderProperty = oderProperty;
    }

    public String getOderProperty() {
        return oderProperty;
    }

    public void setOderType(String oderType) {
        this.oderType = oderType;
    }

    public String getOderType() {
        return oderType;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_merchant_supplier_expand
     *
     * @yougougenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public Criteria setLimitValue(int value1, int value2) {
            if (value2 == 0 )
              throw new RuntimeException("value2 is 0");
            addCriterion("limit",value1,value2,"null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value, property));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIsNull() {
            addCriterion("merchant_code is null");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIsNotNull() {
            addCriterion("merchant_code is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeEqualTo(String value) {
            addCriterion("merchant_code =", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotEqualTo(String value) {
            addCriterion("merchant_code <>", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeGreaterThan(String value) {
            addCriterion("merchant_code >", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_code >=", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLessThan(String value) {
            addCriterion("merchant_code <", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLessThanOrEqualTo(String value) {
            addCriterion("merchant_code <=", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLike(String value) {
            addCriterion("merchant_code like", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotLike(String value) {
            addCriterion("merchant_code not like", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIn(List<String> values) {
            addCriterion("merchant_code in", values, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotIn(List<String> values) {
            addCriterion("merchant_code not in", values, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeBetween(String value1, String value2) {
            addCriterion("merchant_code between", value1, value2, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotBetween(String value1, String value2) {
            addCriterion("merchant_code not between", value1, value2, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityIsNull() {
            addCriterion("safe_stock_quantity is null");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityIsNotNull() {
            addCriterion("safe_stock_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityEqualTo(Integer value) {
            addCriterion("safe_stock_quantity =", value, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityNotEqualTo(Integer value) {
            addCriterion("safe_stock_quantity <>", value, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityGreaterThan(Integer value) {
            addCriterion("safe_stock_quantity >", value, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("safe_stock_quantity >=", value, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityLessThan(Integer value) {
            addCriterion("safe_stock_quantity <", value, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("safe_stock_quantity <=", value, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityIn(List<Integer> values) {
            addCriterion("safe_stock_quantity in", values, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityNotIn(List<Integer> values) {
            addCriterion("safe_stock_quantity not in", values, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityBetween(Integer value1, Integer value2) {
            addCriterion("safe_stock_quantity between", value1, value2, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andSafeStockQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("safe_stock_quantity not between", value1, value2, "safeStockQuantity");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdIsNull() {
            addCriterion("yg_contact_user_id is null");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdIsNotNull() {
            addCriterion("yg_contact_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdEqualTo(String value) {
            addCriterion("yg_contact_user_id =", value, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdNotEqualTo(String value) {
            addCriterion("yg_contact_user_id <>", value, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdGreaterThan(String value) {
            addCriterion("yg_contact_user_id >", value, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("yg_contact_user_id >=", value, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdLessThan(String value) {
            addCriterion("yg_contact_user_id <", value, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdLessThanOrEqualTo(String value) {
            addCriterion("yg_contact_user_id <=", value, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdLike(String value) {
            addCriterion("yg_contact_user_id like", value, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdNotLike(String value) {
            addCriterion("yg_contact_user_id not like", value, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdIn(List<String> values) {
            addCriterion("yg_contact_user_id in", values, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdNotIn(List<String> values) {
            addCriterion("yg_contact_user_id not in", values, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdBetween(String value1, String value2) {
            addCriterion("yg_contact_user_id between", value1, value2, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andYgContactUserIdNotBetween(String value1, String value2) {
            addCriterion("yg_contact_user_id not between", value1, value2, "ygContactUserId");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNull() {
            addCriterion("contract_no is null");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNotNull() {
            addCriterion("contract_no is not null");
            return (Criteria) this;
        }

        public Criteria andContractNoEqualTo(String value) {
            addCriterion("contract_no =", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotEqualTo(String value) {
            addCriterion("contract_no <>", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThan(String value) {
            addCriterion("contract_no >", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThanOrEqualTo(String value) {
            addCriterion("contract_no >=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThan(String value) {
            addCriterion("contract_no <", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThanOrEqualTo(String value) {
            addCriterion("contract_no <=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLike(String value) {
            addCriterion("contract_no like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotLike(String value) {
            addCriterion("contract_no not like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoIn(List<String> values) {
            addCriterion("contract_no in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotIn(List<String> values) {
            addCriterion("contract_no not in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoBetween(String value1, String value2) {
            addCriterion("contract_no between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotBetween(String value1, String value2) {
            addCriterion("contract_no not between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andUptateTimeIsNull() {
            addCriterion("uptate_time is null");
            return (Criteria) this;
        }

        public Criteria andUptateTimeIsNotNull() {
            addCriterion("uptate_time is not null");
            return (Criteria) this;
        }

        public Criteria andUptateTimeEqualTo(String value) {
            addCriterion("uptate_time =", value, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeNotEqualTo(String value) {
            addCriterion("uptate_time <>", value, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeGreaterThan(String value) {
            addCriterion("uptate_time >", value, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("uptate_time >=", value, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeLessThan(String value) {
            addCriterion("uptate_time <", value, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeLessThanOrEqualTo(String value) {
            addCriterion("uptate_time <=", value, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeLike(String value) {
            addCriterion("uptate_time like", value, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeNotLike(String value) {
            addCriterion("uptate_time not like", value, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeIn(List<String> values) {
            addCriterion("uptate_time in", values, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeNotIn(List<String> values) {
            addCriterion("uptate_time not in", values, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeBetween(String value1, String value2) {
            addCriterion("uptate_time between", value1, value2, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andUptateTimeNotBetween(String value1, String value2) {
            addCriterion("uptate_time not between", value1, value2, "uptateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysIsNull() {
            addCriterion("mark_remaining_days is null");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysIsNotNull() {
            addCriterion("mark_remaining_days is not null");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysEqualTo(Integer value) {
            addCriterion("mark_remaining_days =", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysNotEqualTo(Integer value) {
            addCriterion("mark_remaining_days <>", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysGreaterThan(Integer value) {
            addCriterion("mark_remaining_days >", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("mark_remaining_days >=", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysLessThan(Integer value) {
            addCriterion("mark_remaining_days <", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysLessThanOrEqualTo(Integer value) {
            addCriterion("mark_remaining_days <=", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysIn(List<Integer> values) {
            addCriterion("mark_remaining_days in", values, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysNotIn(List<Integer> values) {
            addCriterion("mark_remaining_days not in", values, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysBetween(Integer value1, Integer value2) {
            addCriterion("mark_remaining_days between", value1, value2, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("mark_remaining_days not between", value1, value2, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysIsNull() {
            addCriterion("contract_remaining_days is null");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysIsNotNull() {
            addCriterion("contract_remaining_days is not null");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysEqualTo(Integer value) {
            addCriterion("contract_remaining_days =", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysNotEqualTo(Integer value) {
            addCriterion("contract_remaining_days <>", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysGreaterThan(Integer value) {
            addCriterion("contract_remaining_days >", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("contract_remaining_days >=", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysLessThan(Integer value) {
            addCriterion("contract_remaining_days <", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysLessThanOrEqualTo(Integer value) {
            addCriterion("contract_remaining_days <=", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysIn(List<Integer> values) {
            addCriterion("contract_remaining_days in", values, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysNotIn(List<Integer> values) {
            addCriterion("contract_remaining_days not in", values, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysBetween(Integer value1, Integer value2) {
            addCriterion("contract_remaining_days between", value1, value2, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("contract_remaining_days not between", value1, value2, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysIsNull() {
            addCriterion("business_remaining_days is null");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysIsNotNull() {
            addCriterion("business_remaining_days is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysEqualTo(Integer value) {
            addCriterion("business_remaining_days =", value, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysNotEqualTo(Integer value) {
            addCriterion("business_remaining_days <>", value, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysGreaterThan(Integer value) {
            addCriterion("business_remaining_days >", value, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("business_remaining_days >=", value, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysLessThan(Integer value) {
            addCriterion("business_remaining_days <", value, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysLessThanOrEqualTo(Integer value) {
            addCriterion("business_remaining_days <=", value, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysIn(List<Integer> values) {
            addCriterion("business_remaining_days in", values, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysNotIn(List<Integer> values) {
            addCriterion("business_remaining_days not in", values, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysBetween(Integer value1, Integer value2) {
            addCriterion("business_remaining_days between", value1, value2, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andBusinessRemainingDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("business_remaining_days not between", value1, value2, "businessRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysIsNull() {
            addCriterion("institutional_remaining_days is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysIsNotNull() {
            addCriterion("institutional_remaining_days is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysEqualTo(Integer value) {
            addCriterion("institutional_remaining_days =", value, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysNotEqualTo(Integer value) {
            addCriterion("institutional_remaining_days <>", value, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysGreaterThan(Integer value) {
            addCriterion("institutional_remaining_days >", value, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("institutional_remaining_days >=", value, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysLessThan(Integer value) {
            addCriterion("institutional_remaining_days <", value, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysLessThanOrEqualTo(Integer value) {
            addCriterion("institutional_remaining_days <=", value, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysIn(List<Integer> values) {
            addCriterion("institutional_remaining_days in", values, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysNotIn(List<Integer> values) {
            addCriterion("institutional_remaining_days not in", values, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysBetween(Integer value1, Integer value2) {
            addCriterion("institutional_remaining_days between", value1, value2, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andInstitutionalRemainingDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("institutional_remaining_days not between", value1, value2, "institutionalRemainingDays");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Integer value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Integer value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Integer value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Integer value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Integer value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Integer> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Integer> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Integer value1, Integer value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeIsNull() {
            addCriterion("business_range is null");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeIsNotNull() {
            addCriterion("business_range is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeEqualTo(String value) {
            addCriterion("business_range =", value, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeNotEqualTo(String value) {
            addCriterion("business_range <>", value, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeGreaterThan(String value) {
            addCriterion("business_range >", value, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeGreaterThanOrEqualTo(String value) {
            addCriterion("business_range >=", value, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeLessThan(String value) {
            addCriterion("business_range <", value, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeLessThanOrEqualTo(String value) {
            addCriterion("business_range <=", value, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeLike(String value) {
            addCriterion("business_range like", value, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeNotLike(String value) {
            addCriterion("business_range not like", value, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeIn(List<String> values) {
            addCriterion("business_range in", values, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeNotIn(List<String> values) {
            addCriterion("business_range not in", values, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeBetween(String value1, String value2) {
            addCriterion("business_range between", value1, value2, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessRangeNotBetween(String value1, String value2) {
            addCriterion("business_range not between", value1, value2, "businessRange");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartIsNull() {
            addCriterion("business_validity_start is null");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartIsNotNull() {
            addCriterion("business_validity_start is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartEqualTo(String value) {
            addCriterion("business_validity_start =", value, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartNotEqualTo(String value) {
            addCriterion("business_validity_start <>", value, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartGreaterThan(String value) {
            addCriterion("business_validity_start >", value, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartGreaterThanOrEqualTo(String value) {
            addCriterion("business_validity_start >=", value, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartLessThan(String value) {
            addCriterion("business_validity_start <", value, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartLessThanOrEqualTo(String value) {
            addCriterion("business_validity_start <=", value, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartLike(String value) {
            addCriterion("business_validity_start like", value, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartNotLike(String value) {
            addCriterion("business_validity_start not like", value, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartIn(List<String> values) {
            addCriterion("business_validity_start in", values, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartNotIn(List<String> values) {
            addCriterion("business_validity_start not in", values, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartBetween(String value1, String value2) {
            addCriterion("business_validity_start between", value1, value2, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityStartNotBetween(String value1, String value2) {
            addCriterion("business_validity_start not between", value1, value2, "businessValidityStart");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndIsNull() {
            addCriterion("business_validity_end is null");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndIsNotNull() {
            addCriterion("business_validity_end is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndEqualTo(String value) {
            addCriterion("business_validity_end =", value, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndNotEqualTo(String value) {
            addCriterion("business_validity_end <>", value, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndGreaterThan(String value) {
            addCriterion("business_validity_end >", value, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndGreaterThanOrEqualTo(String value) {
            addCriterion("business_validity_end >=", value, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndLessThan(String value) {
            addCriterion("business_validity_end <", value, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndLessThanOrEqualTo(String value) {
            addCriterion("business_validity_end <=", value, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndLike(String value) {
            addCriterion("business_validity_end like", value, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndNotLike(String value) {
            addCriterion("business_validity_end not like", value, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndIn(List<String> values) {
            addCriterion("business_validity_end in", values, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndNotIn(List<String> values) {
            addCriterion("business_validity_end not in", values, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndBetween(String value1, String value2) {
            addCriterion("business_validity_end between", value1, value2, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBusinessValidityEndNotBetween(String value1, String value2) {
            addCriterion("business_validity_end not between", value1, value2, "businessValidityEnd");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceIsNull() {
            addCriterion("register_province is null");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceIsNotNull() {
            addCriterion("register_province is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceEqualTo(String value) {
            addCriterion("register_province =", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceNotEqualTo(String value) {
            addCriterion("register_province <>", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceGreaterThan(String value) {
            addCriterion("register_province >", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("register_province >=", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceLessThan(String value) {
            addCriterion("register_province <", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceLessThanOrEqualTo(String value) {
            addCriterion("register_province <=", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceLike(String value) {
            addCriterion("register_province like", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceNotLike(String value) {
            addCriterion("register_province not like", value, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceIn(List<String> values) {
            addCriterion("register_province in", values, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceNotIn(List<String> values) {
            addCriterion("register_province not in", values, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceBetween(String value1, String value2) {
            addCriterion("register_province between", value1, value2, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterProvinceNotBetween(String value1, String value2) {
            addCriterion("register_province not between", value1, value2, "registerProvince");
            return (Criteria) this;
        }

        public Criteria andRegisterCityIsNull() {
            addCriterion("register_city is null");
            return (Criteria) this;
        }

        public Criteria andRegisterCityIsNotNull() {
            addCriterion("register_city is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterCityEqualTo(String value) {
            addCriterion("register_city =", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityNotEqualTo(String value) {
            addCriterion("register_city <>", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityGreaterThan(String value) {
            addCriterion("register_city >", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityGreaterThanOrEqualTo(String value) {
            addCriterion("register_city >=", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityLessThan(String value) {
            addCriterion("register_city <", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityLessThanOrEqualTo(String value) {
            addCriterion("register_city <=", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityLike(String value) {
            addCriterion("register_city like", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityNotLike(String value) {
            addCriterion("register_city not like", value, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityIn(List<String> values) {
            addCriterion("register_city in", values, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityNotIn(List<String> values) {
            addCriterion("register_city not in", values, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityBetween(String value1, String value2) {
            addCriterion("register_city between", value1, value2, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterCityNotBetween(String value1, String value2) {
            addCriterion("register_city not between", value1, value2, "registerCity");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaIsNull() {
            addCriterion("register_area is null");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaIsNotNull() {
            addCriterion("register_area is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaEqualTo(String value) {
            addCriterion("register_area =", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaNotEqualTo(String value) {
            addCriterion("register_area <>", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaGreaterThan(String value) {
            addCriterion("register_area >", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaGreaterThanOrEqualTo(String value) {
            addCriterion("register_area >=", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaLessThan(String value) {
            addCriterion("register_area <", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaLessThanOrEqualTo(String value) {
            addCriterion("register_area <=", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaLike(String value) {
            addCriterion("register_area like", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaNotLike(String value) {
            addCriterion("register_area not like", value, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaIn(List<String> values) {
            addCriterion("register_area in", values, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaNotIn(List<String> values) {
            addCriterion("register_area not in", values, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaBetween(String value1, String value2) {
            addCriterion("register_area between", value1, value2, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterAreaNotBetween(String value1, String value2) {
            addCriterion("register_area not between", value1, value2, "registerArea");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsIsNull() {
            addCriterion("register_details is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsIsNotNull() {
            addCriterion("register_details is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsEqualTo(String value) {
            addCriterion("register_details =", value, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsNotEqualTo(String value) {
            addCriterion("register_details <>", value, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsGreaterThan(String value) {
            addCriterion("register_details >", value, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsGreaterThanOrEqualTo(String value) {
            addCriterion("register_details >=", value, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsLessThan(String value) {
            addCriterion("register_details <", value, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsLessThanOrEqualTo(String value) {
            addCriterion("register_details <=", value, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsLike(String value) {
            addCriterion("register_details like", value, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsNotLike(String value) {
            addCriterion("register_details not like", value, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsIn(List<String> values) {
            addCriterion("register_details in", values, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsNotIn(List<String> values) {
            addCriterion("register_details not in", values, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsBetween(String value1, String value2) {
            addCriterion("register_details between", value1, value2, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andRegisterDetailsNotBetween(String value1, String value2) {
            addCriterion("register_details not between", value1, value2, "registerDetails");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartIsNull() {
            addCriterion("institutional_validity_start is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartIsNotNull() {
            addCriterion("institutional_validity_start is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartEqualTo(String value) {
            addCriterion("institutional_validity_start =", value, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartNotEqualTo(String value) {
            addCriterion("institutional_validity_start <>", value, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartGreaterThan(String value) {
            addCriterion("institutional_validity_start >", value, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartGreaterThanOrEqualTo(String value) {
            addCriterion("institutional_validity_start >=", value, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartLessThan(String value) {
            addCriterion("institutional_validity_start <", value, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartLessThanOrEqualTo(String value) {
            addCriterion("institutional_validity_start <=", value, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartLike(String value) {
            addCriterion("institutional_validity_start like", value, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartNotLike(String value) {
            addCriterion("institutional_validity_start not like", value, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartIn(List<String> values) {
            addCriterion("institutional_validity_start in", values, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartNotIn(List<String> values) {
            addCriterion("institutional_validity_start not in", values, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartBetween(String value1, String value2) {
            addCriterion("institutional_validity_start between", value1, value2, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityStartNotBetween(String value1, String value2) {
            addCriterion("institutional_validity_start not between", value1, value2, "institutionalValidityStart");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndIsNull() {
            addCriterion("institutional_validity_end is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndIsNotNull() {
            addCriterion("institutional_validity_end is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndEqualTo(String value) {
            addCriterion("institutional_validity_end =", value, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndNotEqualTo(String value) {
            addCriterion("institutional_validity_end <>", value, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndGreaterThan(String value) {
            addCriterion("institutional_validity_end >", value, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndGreaterThanOrEqualTo(String value) {
            addCriterion("institutional_validity_end >=", value, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndLessThan(String value) {
            addCriterion("institutional_validity_end <", value, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndLessThanOrEqualTo(String value) {
            addCriterion("institutional_validity_end <=", value, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndLike(String value) {
            addCriterion("institutional_validity_end like", value, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndNotLike(String value) {
            addCriterion("institutional_validity_end not like", value, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndIn(List<String> values) {
            addCriterion("institutional_validity_end in", values, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndNotIn(List<String> values) {
            addCriterion("institutional_validity_end not in", values, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndBetween(String value1, String value2) {
            addCriterion("institutional_validity_end between", value1, value2, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andInstitutionalValidityEndNotBetween(String value1, String value2) {
            addCriterion("institutional_validity_end not between", value1, value2, "institutionalValidityEnd");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceIsNull() {
            addCriterion("bank_local_province is null");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceIsNotNull() {
            addCriterion("bank_local_province is not null");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceEqualTo(String value) {
            addCriterion("bank_local_province =", value, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceNotEqualTo(String value) {
            addCriterion("bank_local_province <>", value, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceGreaterThan(String value) {
            addCriterion("bank_local_province >", value, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("bank_local_province >=", value, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceLessThan(String value) {
            addCriterion("bank_local_province <", value, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceLessThanOrEqualTo(String value) {
            addCriterion("bank_local_province <=", value, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceLike(String value) {
            addCriterion("bank_local_province like", value, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceNotLike(String value) {
            addCriterion("bank_local_province not like", value, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceIn(List<String> values) {
            addCriterion("bank_local_province in", values, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceNotIn(List<String> values) {
            addCriterion("bank_local_province not in", values, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceBetween(String value1, String value2) {
            addCriterion("bank_local_province between", value1, value2, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalProvinceNotBetween(String value1, String value2) {
            addCriterion("bank_local_province not between", value1, value2, "bankLocalProvince");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityIsNull() {
            addCriterion("bank_local_city is null");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityIsNotNull() {
            addCriterion("bank_local_city is not null");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityEqualTo(String value) {
            addCriterion("bank_local_city =", value, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityNotEqualTo(String value) {
            addCriterion("bank_local_city <>", value, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityGreaterThan(String value) {
            addCriterion("bank_local_city >", value, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityGreaterThanOrEqualTo(String value) {
            addCriterion("bank_local_city >=", value, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityLessThan(String value) {
            addCriterion("bank_local_city <", value, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityLessThanOrEqualTo(String value) {
            addCriterion("bank_local_city <=", value, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityLike(String value) {
            addCriterion("bank_local_city like", value, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityNotLike(String value) {
            addCriterion("bank_local_city not like", value, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityIn(List<String> values) {
            addCriterion("bank_local_city in", values, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityNotIn(List<String> values) {
            addCriterion("bank_local_city not in", values, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityBetween(String value1, String value2) {
            addCriterion("bank_local_city between", value1, value2, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalCityNotBetween(String value1, String value2) {
            addCriterion("bank_local_city not between", value1, value2, "bankLocalCity");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaIsNull() {
            addCriterion("bank_local_area is null");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaIsNotNull() {
            addCriterion("bank_local_area is not null");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaEqualTo(String value) {
            addCriterion("bank_local_area =", value, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaNotEqualTo(String value) {
            addCriterion("bank_local_area <>", value, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaGreaterThan(String value) {
            addCriterion("bank_local_area >", value, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaGreaterThanOrEqualTo(String value) {
            addCriterion("bank_local_area >=", value, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaLessThan(String value) {
            addCriterion("bank_local_area <", value, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaLessThanOrEqualTo(String value) {
            addCriterion("bank_local_area <=", value, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaLike(String value) {
            addCriterion("bank_local_area like", value, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaNotLike(String value) {
            addCriterion("bank_local_area not like", value, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaIn(List<String> values) {
            addCriterion("bank_local_area in", values, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaNotIn(List<String> values) {
            addCriterion("bank_local_area not in", values, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaBetween(String value1, String value2) {
            addCriterion("bank_local_area between", value1, value2, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andBankLocalAreaNotBetween(String value1, String value2) {
            addCriterion("bank_local_area not between", value1, value2, "bankLocalArea");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIsNull() {
            addCriterion("audit_remark is null");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIsNotNull() {
            addCriterion("audit_remark is not null");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkEqualTo(String value) {
            addCriterion("audit_remark =", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotEqualTo(String value) {
            addCriterion("audit_remark <>", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkGreaterThan(String value) {
            addCriterion("audit_remark >", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("audit_remark >=", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLessThan(String value) {
            addCriterion("audit_remark <", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLessThanOrEqualTo(String value) {
            addCriterion("audit_remark <=", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLike(String value) {
            addCriterion("audit_remark like", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotLike(String value) {
            addCriterion("audit_remark not like", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIn(List<String> values) {
            addCriterion("audit_remark in", values, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotIn(List<String> values) {
            addCriterion("audit_remark not in", values, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkBetween(String value1, String value2) {
            addCriterion("audit_remark between", value1, value2, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotBetween(String value1, String value2) {
            addCriterion("audit_remark not between", value1, value2, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIsNull() {
            addCriterion("supplier_id is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIsNotNull() {
            addCriterion("supplier_id is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierIdEqualTo(String value) {
            addCriterion("supplier_id =", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotEqualTo(String value) {
            addCriterion("supplier_id <>", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdGreaterThan(String value) {
            addCriterion("supplier_id >", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_id >=", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLessThan(String value) {
            addCriterion("supplier_id <", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLessThanOrEqualTo(String value) {
            addCriterion("supplier_id <=", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLike(String value) {
            addCriterion("supplier_id like", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotLike(String value) {
            addCriterion("supplier_id not like", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIn(List<String> values) {
            addCriterion("supplier_id in", values, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotIn(List<String> values) {
            addCriterion("supplier_id not in", values, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdBetween(String value1, String value2) {
            addCriterion("supplier_id between", value1, value2, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotBetween(String value1, String value2) {
            addCriterion("supplier_id not between", value1, value2, "supplierId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_merchant_supplier_expand
     *
     * @yougougenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_merchant_supplier_expand
     *
     * @yougougenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
              this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}