/*
 * 类名 com.yougou.merchant.api.supplier.vo.SupplierContractQuery
 * 
 * 日期  Tue Jun 23 13:25:28 CST 2015
 * 
 * 版权声明Copyright (C) 2013 YouGou Information Technology Co.,Ltd 
 * All Rights Reserved. 
 * 
 * The software for the YouGou technology development, without the 
 * company's written consent, and any other individuals and 
 * organizations shall not be used, Copying, Modify or distribute 
 * the software.
 * 
 */
package com.yougou.merchant.api.supplier.vo;

import java.math.BigDecimal;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import org.apache.commons.lang.StringUtils;

public class SupplierContractQuery {
    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_sp_supplier_contract
     *
     * @yougougenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_sp_supplier_contract
     *
     * @yougougenerated
     */
    protected String oderProperty;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_sp_supplier_contract
     *
     * @yougougenerated
     */
    protected String oderType;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_sp_supplier_contract
     *
     * @yougougenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_sp_supplier_contract
     *
     * @yougougenerated
     */
    protected List<Criteria> oredCriteria;

    public SupplierContractQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        if (StringUtils.isEmpty(orderByClause) && StringUtils.isNotEmpty(this.getOderProperty()) && StringUtils.isNotEmpty(this.getOderType())){
            return MessageFormat.format("{0} {1}", this.getOderProperty(),this.getOderType());
        }
        return orderByClause;
    }

    public void setOderProperty(String oderProperty) {
        this.oderProperty = oderProperty;
    }

    public String getOderProperty() {
        return oderProperty;
    }

    public void setOderType(String oderType) {
        this.oderType = oderType;
    }

    public String getOderType() {
        return oderType;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_sp_supplier_contract
     *
     * @yougougenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public Criteria setLimitValue(int value1, int value2) {
            if (value2 == 0 )
              throw new RuntimeException("value2 is 0");
            addCriterion("limit",value1,value2,"null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value, property));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIsNull() {
            addCriterion("supplier_id is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIsNotNull() {
            addCriterion("supplier_id is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierIdEqualTo(String value) {
            addCriterion("supplier_id =", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotEqualTo(String value) {
            addCriterion("supplier_id <>", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdGreaterThan(String value) {
            addCriterion("supplier_id >", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_id >=", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLessThan(String value) {
            addCriterion("supplier_id <", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLessThanOrEqualTo(String value) {
            addCriterion("supplier_id <=", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLike(String value) {
            addCriterion("supplier_id like", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotLike(String value) {
            addCriterion("supplier_id not like", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIn(List<String> values) {
            addCriterion("supplier_id in", values, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotIn(List<String> values) {
            addCriterion("supplier_id not in", values, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdBetween(String value1, String value2) {
            addCriterion("supplier_id between", value1, value2, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotBetween(String value1, String value2) {
            addCriterion("supplier_id not between", value1, value2, "supplierId");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNull() {
            addCriterion("contract_no is null");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNotNull() {
            addCriterion("contract_no is not null");
            return (Criteria) this;
        }

        public Criteria andContractNoEqualTo(String value) {
            addCriterion("contract_no =", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotEqualTo(String value) {
            addCriterion("contract_no <>", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThan(String value) {
            addCriterion("contract_no >", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThanOrEqualTo(String value) {
            addCriterion("contract_no >=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThan(String value) {
            addCriterion("contract_no <", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThanOrEqualTo(String value) {
            addCriterion("contract_no <=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLike(String value) {
            addCriterion("contract_no like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotLike(String value) {
            addCriterion("contract_no not like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoIn(List<String> values) {
            addCriterion("contract_no in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotIn(List<String> values) {
            addCriterion("contract_no not in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoBetween(String value1, String value2) {
            addCriterion("contract_no between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotBetween(String value1, String value2) {
            addCriterion("contract_no not between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andClearingFormIsNull() {
            addCriterion("clearing_form is null");
            return (Criteria) this;
        }

        public Criteria andClearingFormIsNotNull() {
            addCriterion("clearing_form is not null");
            return (Criteria) this;
        }

        public Criteria andClearingFormEqualTo(Short value) {
            addCriterion("clearing_form =", value, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andClearingFormNotEqualTo(Short value) {
            addCriterion("clearing_form <>", value, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andClearingFormGreaterThan(Short value) {
            addCriterion("clearing_form >", value, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andClearingFormGreaterThanOrEqualTo(Short value) {
            addCriterion("clearing_form >=", value, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andClearingFormLessThan(Short value) {
            addCriterion("clearing_form <", value, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andClearingFormLessThanOrEqualTo(Short value) {
            addCriterion("clearing_form <=", value, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andClearingFormIn(List<Short> values) {
            addCriterion("clearing_form in", values, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andClearingFormNotIn(List<Short> values) {
            addCriterion("clearing_form not in", values, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andClearingFormBetween(Short value1, Short value2) {
            addCriterion("clearing_form between", value1, value2, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andClearingFormNotBetween(Short value1, Short value2) {
            addCriterion("clearing_form not between", value1, value2, "clearingForm");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateIsNull() {
            addCriterion("effective_date is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateIsNotNull() {
            addCriterion("effective_date is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateEqualTo(Date value) {
            addCriterionForJDBCDate("effective_date =", value, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("effective_date <>", value, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateGreaterThan(Date value) {
            addCriterionForJDBCDate("effective_date >", value, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("effective_date >=", value, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateLessThan(Date value) {
            addCriterionForJDBCDate("effective_date <", value, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("effective_date <=", value, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateIn(List<Date> values) {
            addCriterionForJDBCDate("effective_date in", values, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("effective_date not in", values, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("effective_date between", value1, value2, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andEffectiveDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("effective_date not between", value1, value2, "effectiveDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateIsNull() {
            addCriterion("failure_date is null");
            return (Criteria) this;
        }

        public Criteria andFailureDateIsNotNull() {
            addCriterion("failure_date is not null");
            return (Criteria) this;
        }

        public Criteria andFailureDateEqualTo(Date value) {
            addCriterionForJDBCDate("failure_date =", value, "failureDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("failure_date <>", value, "failureDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateGreaterThan(Date value) {
            addCriterionForJDBCDate("failure_date >", value, "failureDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("failure_date >=", value, "failureDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateLessThan(Date value) {
            addCriterionForJDBCDate("failure_date <", value, "failureDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("failure_date <=", value, "failureDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateIn(List<Date> values) {
            addCriterionForJDBCDate("failure_date in", values, "failureDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("failure_date not in", values, "failureDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("failure_date between", value1, value2, "failureDate");
            return (Criteria) this;
        }

        public Criteria andFailureDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("failure_date not between", value1, value2, "failureDate");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andAttachmentIsNull() {
            addCriterion("attachment is null");
            return (Criteria) this;
        }

        public Criteria andAttachmentIsNotNull() {
            addCriterion("attachment is not null");
            return (Criteria) this;
        }

        public Criteria andAttachmentEqualTo(String value) {
            addCriterion("attachment =", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotEqualTo(String value) {
            addCriterion("attachment <>", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentGreaterThan(String value) {
            addCriterion("attachment >", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentGreaterThanOrEqualTo(String value) {
            addCriterion("attachment >=", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentLessThan(String value) {
            addCriterion("attachment <", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentLessThanOrEqualTo(String value) {
            addCriterion("attachment <=", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentLike(String value) {
            addCriterion("attachment like", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotLike(String value) {
            addCriterion("attachment not like", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentIn(List<String> values) {
            addCriterion("attachment in", values, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotIn(List<String> values) {
            addCriterion("attachment not in", values, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentBetween(String value1, String value2) {
            addCriterion("attachment between", value1, value2, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotBetween(String value1, String value2) {
            addCriterion("attachment not between", value1, value2, "attachment");
            return (Criteria) this;
        }

        public Criteria andDeclarantIsNull() {
            addCriterion("declarant is null");
            return (Criteria) this;
        }

        public Criteria andDeclarantIsNotNull() {
            addCriterion("declarant is not null");
            return (Criteria) this;
        }

        public Criteria andDeclarantEqualTo(String value) {
            addCriterion("declarant =", value, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantNotEqualTo(String value) {
            addCriterion("declarant <>", value, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantGreaterThan(String value) {
            addCriterion("declarant >", value, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantGreaterThanOrEqualTo(String value) {
            addCriterion("declarant >=", value, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantLessThan(String value) {
            addCriterion("declarant <", value, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantLessThanOrEqualTo(String value) {
            addCriterion("declarant <=", value, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantLike(String value) {
            addCriterion("declarant like", value, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantNotLike(String value) {
            addCriterion("declarant not like", value, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantIn(List<String> values) {
            addCriterion("declarant in", values, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantNotIn(List<String> values) {
            addCriterion("declarant not in", values, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantBetween(String value1, String value2) {
            addCriterion("declarant between", value1, value2, "declarant");
            return (Criteria) this;
        }

        public Criteria andDeclarantNotBetween(String value1, String value2) {
            addCriterion("declarant not between", value1, value2, "declarant");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andBindStatusIsNull() {
            addCriterion("bind_status is null");
            return (Criteria) this;
        }

        public Criteria andBindStatusIsNotNull() {
            addCriterion("bind_status is not null");
            return (Criteria) this;
        }

        public Criteria andBindStatusEqualTo(String value) {
            addCriterion("bind_status =", value, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusNotEqualTo(String value) {
            addCriterion("bind_status <>", value, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusGreaterThan(String value) {
            addCriterion("bind_status >", value, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusGreaterThanOrEqualTo(String value) {
            addCriterion("bind_status >=", value, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusLessThan(String value) {
            addCriterion("bind_status <", value, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusLessThanOrEqualTo(String value) {
            addCriterion("bind_status <=", value, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusLike(String value) {
            addCriterion("bind_status like", value, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusNotLike(String value) {
            addCriterion("bind_status not like", value, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusIn(List<String> values) {
            addCriterion("bind_status in", values, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusNotIn(List<String> values) {
            addCriterion("bind_status not in", values, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusBetween(String value1, String value2) {
            addCriterion("bind_status between", value1, value2, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andBindStatusNotBetween(String value1, String value2) {
            addCriterion("bind_status not between", value1, value2, "bindStatus");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNull() {
            addCriterion("supplier is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNotNull() {
            addCriterion("supplier is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierEqualTo(String value) {
            addCriterion("supplier =", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotEqualTo(String value) {
            addCriterion("supplier <>", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThan(String value) {
            addCriterion("supplier >", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("supplier >=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThan(String value) {
            addCriterion("supplier <", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThanOrEqualTo(String value) {
            addCriterion("supplier <=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLike(String value) {
            addCriterion("supplier like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotLike(String value) {
            addCriterion("supplier not like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierIn(List<String> values) {
            addCriterion("supplier in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotIn(List<String> values) {
            addCriterion("supplier not in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierBetween(String value1, String value2) {
            addCriterion("supplier between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotBetween(String value1, String value2) {
            addCriterion("supplier not between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysIsNull() {
            addCriterion("mark_remaining_days is null");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysIsNotNull() {
            addCriterion("mark_remaining_days is not null");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysEqualTo(Integer value) {
            addCriterion("mark_remaining_days =", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysNotEqualTo(Integer value) {
            addCriterion("mark_remaining_days <>", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysGreaterThan(Integer value) {
            addCriterion("mark_remaining_days >", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("mark_remaining_days >=", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysLessThan(Integer value) {
            addCriterion("mark_remaining_days <", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysLessThanOrEqualTo(Integer value) {
            addCriterion("mark_remaining_days <=", value, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysIn(List<Integer> values) {
            addCriterion("mark_remaining_days in", values, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysNotIn(List<Integer> values) {
            addCriterion("mark_remaining_days not in", values, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysBetween(Integer value1, Integer value2) {
            addCriterion("mark_remaining_days between", value1, value2, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andMarkRemainingDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("mark_remaining_days not between", value1, value2, "markRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysIsNull() {
            addCriterion("contract_remaining_days is null");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysIsNotNull() {
            addCriterion("contract_remaining_days is not null");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysEqualTo(Integer value) {
            addCriterion("contract_remaining_days =", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysNotEqualTo(Integer value) {
            addCriterion("contract_remaining_days <>", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysGreaterThan(Integer value) {
            addCriterion("contract_remaining_days >", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("contract_remaining_days >=", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysLessThan(Integer value) {
            addCriterion("contract_remaining_days <", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysLessThanOrEqualTo(Integer value) {
            addCriterion("contract_remaining_days <=", value, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysIn(List<Integer> values) {
            addCriterion("contract_remaining_days in", values, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysNotIn(List<Integer> values) {
            addCriterion("contract_remaining_days not in", values, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysBetween(Integer value1, Integer value2) {
            addCriterion("contract_remaining_days between", value1, value2, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andContractRemainingDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("contract_remaining_days not between", value1, value2, "contractRemainingDays");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewIsNull() {
            addCriterion("is_Need_Renew is null");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewIsNotNull() {
            addCriterion("is_Need_Renew is not null");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewEqualTo(String value) {
            addCriterion("is_Need_Renew =", value, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewNotEqualTo(String value) {
            addCriterion("is_Need_Renew <>", value, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewGreaterThan(String value) {
            addCriterion("is_Need_Renew >", value, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewGreaterThanOrEqualTo(String value) {
            addCriterion("is_Need_Renew >=", value, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewLessThan(String value) {
            addCriterion("is_Need_Renew <", value, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewLessThanOrEqualTo(String value) {
            addCriterion("is_Need_Renew <=", value, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewLike(String value) {
            addCriterion("is_Need_Renew like", value, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewNotLike(String value) {
            addCriterion("is_Need_Renew not like", value, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewIn(List<String> values) {
            addCriterion("is_Need_Renew in", values, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewNotIn(List<String> values) {
            addCriterion("is_Need_Renew not in", values, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewBetween(String value1, String value2) {
            addCriterion("is_Need_Renew between", value1, value2, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsNeedRenewNotBetween(String value1, String value2) {
            addCriterion("is_Need_Renew not between", value1, value2, "isNeedRenew");
            return (Criteria) this;
        }

        public Criteria andIsUseErpIsNull() {
            addCriterion("is_Use_ERP is null");
            return (Criteria) this;
        }

        public Criteria andIsUseErpIsNotNull() {
            addCriterion("is_Use_ERP is not null");
            return (Criteria) this;
        }

        public Criteria andIsUseErpEqualTo(String value) {
            addCriterion("is_Use_ERP =", value, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpNotEqualTo(String value) {
            addCriterion("is_Use_ERP <>", value, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpGreaterThan(String value) {
            addCriterion("is_Use_ERP >", value, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpGreaterThanOrEqualTo(String value) {
            addCriterion("is_Use_ERP >=", value, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpLessThan(String value) {
            addCriterion("is_Use_ERP <", value, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpLessThanOrEqualTo(String value) {
            addCriterion("is_Use_ERP <=", value, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpLike(String value) {
            addCriterion("is_Use_ERP like", value, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpNotLike(String value) {
            addCriterion("is_Use_ERP not like", value, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpIn(List<String> values) {
            addCriterion("is_Use_ERP in", values, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpNotIn(List<String> values) {
            addCriterion("is_Use_ERP not in", values, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpBetween(String value1, String value2) {
            addCriterion("is_Use_ERP between", value1, value2, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsUseErpNotBetween(String value1, String value2) {
            addCriterion("is_Use_ERP not between", value1, value2, "isUseErp");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositIsNull() {
            addCriterion("is_Need_Deposit is null");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositIsNotNull() {
            addCriterion("is_Need_Deposit is not null");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositEqualTo(String value) {
            addCriterion("is_Need_Deposit =", value, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositNotEqualTo(String value) {
            addCriterion("is_Need_Deposit <>", value, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositGreaterThan(String value) {
            addCriterion("is_Need_Deposit >", value, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositGreaterThanOrEqualTo(String value) {
            addCriterion("is_Need_Deposit >=", value, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositLessThan(String value) {
            addCriterion("is_Need_Deposit <", value, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositLessThanOrEqualTo(String value) {
            addCriterion("is_Need_Deposit <=", value, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositLike(String value) {
            addCriterion("is_Need_Deposit like", value, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositNotLike(String value) {
            addCriterion("is_Need_Deposit not like", value, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositIn(List<String> values) {
            addCriterion("is_Need_Deposit in", values, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositNotIn(List<String> values) {
            addCriterion("is_Need_Deposit not in", values, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositBetween(String value1, String value2) {
            addCriterion("is_Need_Deposit between", value1, value2, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedDepositNotBetween(String value1, String value2) {
            addCriterion("is_Need_Deposit not between", value1, value2, "isNeedDeposit");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeIsNull() {
            addCriterion("is_need_use_fee is null");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeIsNotNull() {
            addCriterion("is_need_use_fee is not null");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeEqualTo(String value) {
            addCriterion("is_need_use_fee =", value, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeNotEqualTo(String value) {
            addCriterion("is_need_use_fee <>", value, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeGreaterThan(String value) {
            addCriterion("is_need_use_fee >", value, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeGreaterThanOrEqualTo(String value) {
            addCriterion("is_need_use_fee >=", value, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeLessThan(String value) {
            addCriterion("is_need_use_fee <", value, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeLessThanOrEqualTo(String value) {
            addCriterion("is_need_use_fee <=", value, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeLike(String value) {
            addCriterion("is_need_use_fee like", value, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeNotLike(String value) {
            addCriterion("is_need_use_fee not like", value, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeIn(List<String> values) {
            addCriterion("is_need_use_fee in", values, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeNotIn(List<String> values) {
            addCriterion("is_need_use_fee not in", values, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeBetween(String value1, String value2) {
            addCriterion("is_need_use_fee between", value1, value2, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andIsNeedUseFeeNotBetween(String value1, String value2) {
            addCriterion("is_need_use_fee not between", value1, value2, "isNeedUseFee");
            return (Criteria) this;
        }

        public Criteria andDepositIsNull() {
            addCriterion("deposit is null");
            return (Criteria) this;
        }

        public Criteria andDepositIsNotNull() {
            addCriterion("deposit is not null");
            return (Criteria) this;
        }

        public Criteria andDepositEqualTo(BigDecimal value) {
            addCriterion("deposit =", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotEqualTo(BigDecimal value) {
            addCriterion("deposit <>", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThan(BigDecimal value) {
            addCriterion("deposit >", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("deposit >=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThan(BigDecimal value) {
            addCriterion("deposit <", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThanOrEqualTo(BigDecimal value) {
            addCriterion("deposit <=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositIn(List<BigDecimal> values) {
            addCriterion("deposit in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotIn(List<BigDecimal> values) {
            addCriterion("deposit not in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deposit between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("deposit not between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andUseFeeIsNull() {
            addCriterion("use_fee is null");
            return (Criteria) this;
        }

        public Criteria andUseFeeIsNotNull() {
            addCriterion("use_fee is not null");
            return (Criteria) this;
        }

        public Criteria andUseFeeEqualTo(BigDecimal value) {
            addCriterion("use_fee =", value, "useFee");
            return (Criteria) this;
        }

        public Criteria andUseFeeNotEqualTo(BigDecimal value) {
            addCriterion("use_fee <>", value, "useFee");
            return (Criteria) this;
        }

        public Criteria andUseFeeGreaterThan(BigDecimal value) {
            addCriterion("use_fee >", value, "useFee");
            return (Criteria) this;
        }

        public Criteria andUseFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("use_fee >=", value, "useFee");
            return (Criteria) this;
        }

        public Criteria andUseFeeLessThan(BigDecimal value) {
            addCriterion("use_fee <", value, "useFee");
            return (Criteria) this;
        }

        public Criteria andUseFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("use_fee <=", value, "useFee");
            return (Criteria) this;
        }

        public Criteria andUseFeeIn(List<BigDecimal> values) {
            addCriterion("use_fee in", values, "useFee");
            return (Criteria) this;
        }

        public Criteria andUseFeeNotIn(List<BigDecimal> values) {
            addCriterion("use_fee not in", values, "useFee");
            return (Criteria) this;
        }

        public Criteria andUseFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("use_fee between", value1, value2, "useFee");
            return (Criteria) this;
        }

        public Criteria andUseFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("use_fee not between", value1, value2, "useFee");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andBankOwnerIsNull() {
            addCriterion("bank_owner is null");
            return (Criteria) this;
        }

        public Criteria andBankOwnerIsNotNull() {
            addCriterion("bank_owner is not null");
            return (Criteria) this;
        }

        public Criteria andBankOwnerEqualTo(String value) {
            addCriterion("bank_owner =", value, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerNotEqualTo(String value) {
            addCriterion("bank_owner <>", value, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerGreaterThan(String value) {
            addCriterion("bank_owner >", value, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("bank_owner >=", value, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerLessThan(String value) {
            addCriterion("bank_owner <", value, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerLessThanOrEqualTo(String value) {
            addCriterion("bank_owner <=", value, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerLike(String value) {
            addCriterion("bank_owner like", value, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerNotLike(String value) {
            addCriterion("bank_owner not like", value, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerIn(List<String> values) {
            addCriterion("bank_owner in", values, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerNotIn(List<String> values) {
            addCriterion("bank_owner not in", values, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerBetween(String value1, String value2) {
            addCriterion("bank_owner between", value1, value2, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankOwnerNotBetween(String value1, String value2) {
            addCriterion("bank_owner not between", value1, value2, "bankOwner");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNull() {
            addCriterion("bank_account is null");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNotNull() {
            addCriterion("bank_account is not null");
            return (Criteria) this;
        }

        public Criteria andBankAccountEqualTo(String value) {
            addCriterion("bank_account =", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotEqualTo(String value) {
            addCriterion("bank_account <>", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThan(String value) {
            addCriterion("bank_account >", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThanOrEqualTo(String value) {
            addCriterion("bank_account >=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThan(String value) {
            addCriterion("bank_account <", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThanOrEqualTo(String value) {
            addCriterion("bank_account <=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLike(String value) {
            addCriterion("bank_account like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotLike(String value) {
            addCriterion("bank_account not like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountIn(List<String> values) {
            addCriterion("bank_account in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotIn(List<String> values) {
            addCriterion("bank_account not in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountBetween(String value1, String value2) {
            addCriterion("bank_account between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotBetween(String value1, String value2) {
            addCriterion("bank_account not between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankProvinceIsNull() {
            addCriterion("bank_province is null");
            return (Criteria) this;
        }

        public Criteria andBankProvinceIsNotNull() {
            addCriterion("bank_province is not null");
            return (Criteria) this;
        }

        public Criteria andBankProvinceEqualTo(String value) {
            addCriterion("bank_province =", value, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceNotEqualTo(String value) {
            addCriterion("bank_province <>", value, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceGreaterThan(String value) {
            addCriterion("bank_province >", value, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("bank_province >=", value, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceLessThan(String value) {
            addCriterion("bank_province <", value, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceLessThanOrEqualTo(String value) {
            addCriterion("bank_province <=", value, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceLike(String value) {
            addCriterion("bank_province like", value, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceNotLike(String value) {
            addCriterion("bank_province not like", value, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceIn(List<String> values) {
            addCriterion("bank_province in", values, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceNotIn(List<String> values) {
            addCriterion("bank_province not in", values, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceBetween(String value1, String value2) {
            addCriterion("bank_province between", value1, value2, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankProvinceNotBetween(String value1, String value2) {
            addCriterion("bank_province not between", value1, value2, "bankProvince");
            return (Criteria) this;
        }

        public Criteria andBankCityIsNull() {
            addCriterion("bank_city is null");
            return (Criteria) this;
        }

        public Criteria andBankCityIsNotNull() {
            addCriterion("bank_city is not null");
            return (Criteria) this;
        }

        public Criteria andBankCityEqualTo(String value) {
            addCriterion("bank_city =", value, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityNotEqualTo(String value) {
            addCriterion("bank_city <>", value, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityGreaterThan(String value) {
            addCriterion("bank_city >", value, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityGreaterThanOrEqualTo(String value) {
            addCriterion("bank_city >=", value, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityLessThan(String value) {
            addCriterion("bank_city <", value, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityLessThanOrEqualTo(String value) {
            addCriterion("bank_city <=", value, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityLike(String value) {
            addCriterion("bank_city like", value, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityNotLike(String value) {
            addCriterion("bank_city not like", value, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityIn(List<String> values) {
            addCriterion("bank_city in", values, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityNotIn(List<String> values) {
            addCriterion("bank_city not in", values, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityBetween(String value1, String value2) {
            addCriterion("bank_city between", value1, value2, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankCityNotBetween(String value1, String value2) {
            addCriterion("bank_city not between", value1, value2, "bankCity");
            return (Criteria) this;
        }

        public Criteria andBankAreaIsNull() {
            addCriterion("bank_area is null");
            return (Criteria) this;
        }

        public Criteria andBankAreaIsNotNull() {
            addCriterion("bank_area is not null");
            return (Criteria) this;
        }

        public Criteria andBankAreaEqualTo(String value) {
            addCriterion("bank_area =", value, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaNotEqualTo(String value) {
            addCriterion("bank_area <>", value, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaGreaterThan(String value) {
            addCriterion("bank_area >", value, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaGreaterThanOrEqualTo(String value) {
            addCriterion("bank_area >=", value, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaLessThan(String value) {
            addCriterion("bank_area <", value, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaLessThanOrEqualTo(String value) {
            addCriterion("bank_area <=", value, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaLike(String value) {
            addCriterion("bank_area like", value, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaNotLike(String value) {
            addCriterion("bank_area not like", value, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaIn(List<String> values) {
            addCriterion("bank_area in", values, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaNotIn(List<String> values) {
            addCriterion("bank_area not in", values, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaBetween(String value1, String value2) {
            addCriterion("bank_area between", value1, value2, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankAreaNotBetween(String value1, String value2) {
            addCriterion("bank_area not between", value1, value2, "bankArea");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("bank_name is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("bank_name is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("bank_name =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("bank_name <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("bank_name >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("bank_name >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("bank_name <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("bank_name <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("bank_name like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("bank_name not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("bank_name in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("bank_name not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("bank_name between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("bank_name not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andParentContractIdIsNull() {
            addCriterion("parent_contract_id is null");
            return (Criteria) this;
        }

        public Criteria andParentContractIdIsNotNull() {
            addCriterion("parent_contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentContractIdEqualTo(String value) {
            addCriterion("parent_contract_id =", value, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdNotEqualTo(String value) {
            addCriterion("parent_contract_id <>", value, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdGreaterThan(String value) {
            addCriterion("parent_contract_id >", value, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_contract_id >=", value, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdLessThan(String value) {
            addCriterion("parent_contract_id <", value, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdLessThanOrEqualTo(String value) {
            addCriterion("parent_contract_id <=", value, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdLike(String value) {
            addCriterion("parent_contract_id like", value, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdNotLike(String value) {
            addCriterion("parent_contract_id not like", value, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdIn(List<String> values) {
            addCriterion("parent_contract_id in", values, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdNotIn(List<String> values) {
            addCriterion("parent_contract_id not in", values, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdBetween(String value1, String value2) {
            addCriterion("parent_contract_id between", value1, value2, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andParentContractIdNotBetween(String value1, String value2) {
            addCriterion("parent_contract_id not between", value1, value2, "parentContractId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPreDepositIsNull() {
            addCriterion("pre_deposit is null");
            return (Criteria) this;
        }

        public Criteria andPreDepositIsNotNull() {
            addCriterion("pre_deposit is not null");
            return (Criteria) this;
        }

        public Criteria andPreDepositEqualTo(BigDecimal value) {
            addCriterion("pre_deposit =", value, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreDepositNotEqualTo(BigDecimal value) {
            addCriterion("pre_deposit <>", value, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreDepositGreaterThan(BigDecimal value) {
            addCriterion("pre_deposit >", value, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreDepositGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pre_deposit >=", value, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreDepositLessThan(BigDecimal value) {
            addCriterion("pre_deposit <", value, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreDepositLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pre_deposit <=", value, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreDepositIn(List<BigDecimal> values) {
            addCriterion("pre_deposit in", values, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreDepositNotIn(List<BigDecimal> values) {
            addCriterion("pre_deposit not in", values, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreDepositBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pre_deposit between", value1, value2, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreDepositNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pre_deposit not between", value1, value2, "preDeposit");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeIsNull() {
            addCriterion("pre_useFee is null");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeIsNotNull() {
            addCriterion("pre_useFee is not null");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeEqualTo(BigDecimal value) {
            addCriterion("pre_useFee =", value, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeNotEqualTo(BigDecimal value) {
            addCriterion("pre_useFee <>", value, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeGreaterThan(BigDecimal value) {
            addCriterion("pre_useFee >", value, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pre_useFee >=", value, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeLessThan(BigDecimal value) {
            addCriterion("pre_useFee <", value, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pre_useFee <=", value, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeIn(List<BigDecimal> values) {
            addCriterion("pre_useFee in", values, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeNotIn(List<BigDecimal> values) {
            addCriterion("pre_useFee not in", values, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pre_useFee between", value1, value2, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andPreUsefeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pre_useFee not between", value1, value2, "preUsefee");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositIsNull() {
            addCriterion("is_Transfer_Deposit is null");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositIsNotNull() {
            addCriterion("is_Transfer_Deposit is not null");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositEqualTo(String value) {
            addCriterion("is_Transfer_Deposit =", value, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositNotEqualTo(String value) {
            addCriterion("is_Transfer_Deposit <>", value, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositGreaterThan(String value) {
            addCriterion("is_Transfer_Deposit >", value, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositGreaterThanOrEqualTo(String value) {
            addCriterion("is_Transfer_Deposit >=", value, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositLessThan(String value) {
            addCriterion("is_Transfer_Deposit <", value, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositLessThanOrEqualTo(String value) {
            addCriterion("is_Transfer_Deposit <=", value, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositLike(String value) {
            addCriterion("is_Transfer_Deposit like", value, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositNotLike(String value) {
            addCriterion("is_Transfer_Deposit not like", value, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositIn(List<String> values) {
            addCriterion("is_Transfer_Deposit in", values, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositNotIn(List<String> values) {
            addCriterion("is_Transfer_Deposit not in", values, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositBetween(String value1, String value2) {
            addCriterion("is_Transfer_Deposit between", value1, value2, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andIsTransferDepositNotBetween(String value1, String value2) {
            addCriterion("is_Transfer_Deposit not between", value1, value2, "isTransferDeposit");
            return (Criteria) this;
        }

        public Criteria andRenewFlagIsNull() {
            addCriterion("renew_flag is null");
            return (Criteria) this;
        }

        public Criteria andRenewFlagIsNotNull() {
            addCriterion("renew_flag is not null");
            return (Criteria) this;
        }

        public Criteria andRenewFlagEqualTo(String value) {
            addCriterion("renew_flag =", value, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagNotEqualTo(String value) {
            addCriterion("renew_flag <>", value, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagGreaterThan(String value) {
            addCriterion("renew_flag >", value, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagGreaterThanOrEqualTo(String value) {
            addCriterion("renew_flag >=", value, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagLessThan(String value) {
            addCriterion("renew_flag <", value, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagLessThanOrEqualTo(String value) {
            addCriterion("renew_flag <=", value, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagLike(String value) {
            addCriterion("renew_flag like", value, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagNotLike(String value) {
            addCriterion("renew_flag not like", value, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagIn(List<String> values) {
            addCriterion("renew_flag in", values, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagNotIn(List<String> values) {
            addCriterion("renew_flag not in", values, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagBetween(String value1, String value2) {
            addCriterion("renew_flag between", value1, value2, "renewFlag");
            return (Criteria) this;
        }

        public Criteria andRenewFlagNotBetween(String value1, String value2) {
            addCriterion("renew_flag not between", value1, value2, "renewFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_sp_supplier_contract
     *
     * @yougougenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_sp_supplier_contract
     *
     * @yougougenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
              this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}